# syntax=docker/dockerfile:1
FROM node:16.17.0-alpine
WORKDIR  /client
RUN apk add bash
COPY ./client/package.json ./package.json
RUN npm cache verify && npm install 
COPY ./client .
EXPOSE 4200
CMD ["npm", "start"]