version: "3.9"
services:
  web-server:
    build: 
      context: .
      dockerfile: server/Dockerfile.server
    hostname: web-server
    volumes:
      -  ./server:/server
    ports:
      - "6001:6001"
    devices: 
      - dev/bus/usb:/dev/bus/usb

  client-server:
    build: 
      context: .
      dockerfile: client/Dockerfile.client
    volumes:
      -  ./client:/client
    hostname: client-server
    ports:
      - "4200:4200"
    depends_on:
      - web-server

  simulator:
    build: 
      context: .
      dockerfile: simulator/Dockerfile
    volumes:
      -  ./simulator:/simulator
    hostname: simulator
    ports:
        - "3000:3000"
        - "8000:8000"
        # - "6001:6001"
    depends_on:
      - web-server
      - client-server
    extra_hosts:
      - "host.docker.internal:host-gateway"